'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Activity, BarChart3, CheckCircle2, FileText, LayoutDashboard, RefreshCw, Settings2, TrendingUp } from 'lucide-react';
import { Bar, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Report } from '@/lib/types';

const fmt = (n: number | undefined) => new Intl.NumberFormat('en-US').format(n ?? 0);
const pct = (n: number | undefined) => `${(n ?? 0).toFixed(1)}%`;
const dateLabel = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(`${value}T12:00:00`));

function insight(report?: Report) {
  if (!report) return 'No validated reporting period has been ingested yet.';
  const exceptions = report.exceptions_data || [];
  if (!exceptions.length) return 'The latest period is operating within the configured exception thresholds.';
  const rank = (s: string) => s === 'HIGH' ? 2 : s === 'MEDIUM' ? 1 : 0;
  const worst = [...exceptions].sort((a,b) => rank(b.severity) - rank(a.severity))[0];
  return `${exceptions.length} operational signal${exceptions.length > 1 ? 's' : ''} detected. The strongest signal is ${worst.production_line_id} · ${worst.type.replaceAll('_', ' ').toLowerCase()}.`;
}

export default function Dashboard() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/dashboard', { cache: 'no-store' }); const json = await res.json(); if (!res.ok || !json.success) throw new Error(json.error || 'Failed to load reports'); setReports(json.reports || []); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load dashboard'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const latest = reports[0]; const kpi = latest?.kpi_data || {}; const exceptions = latest?.exceptions_data || [];
  const trend = useMemo(() => [...reports].reverse().map(r => ({ period: dateLabel(r.period_end), attainment: Number(r.kpi_data?.target_attainment ?? 0), quality: Number(r.kpi_data?.quality_rate ?? 0) })), [reports]);
  const production = latest ? [{ name: 'Target', value: latest.kpi_data?.target_units ?? 0 }, { name: 'Produced', value: latest.kpi_data?.produced_units ?? 0 }, { name: 'Good', value: latest.kpi_data?.good_units ?? 0 }] : [];
  const qualityMix = latest ? [{ name: 'Good', value: latest.kpi_data?.good_units ?? 0 }, { name: 'Non-good', value: Math.max(0, (latest.kpi_data?.produced_units ?? 0) - (latest.kpi_data?.good_units ?? 0)) }] : [];
  const lineExceptions = useMemo(() => { const map = new Map<string, number>(); exceptions.forEach(e => map.set(e.production_line_id, (map.get(e.production_line_id) || 0) + 1)); return [...map.entries()].map(([line, count]) => ({ line, count })).sort((a,b) => b.count-a.count); }, [exceptions]);
  if (loading) return <div className="loading"><Activity size={18}/> Loading operational intelligence…</div>;

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">IO</div><div className="brand-copy"><strong>Industrial Ops</strong><span>Command Center</span></div></div><nav className="nav"><a className="active" href="#overview"><LayoutDashboard size={16}/><span>Overview</span></a><a href="#performance"><BarChart3 size={16}/><span>Performance</span></a><a href="#reports"><FileText size={16}/><span>Reports</span></a><Link href="/settings"><Settings2 size={16}/><span>Configuration</span></Link></nav><div className="side-foot">VALIDATED DATA<br/>Automated reporting layer</div></aside>
    <main className="main">
      <header className="topbar"><div><div className="eyebrow">Operations intelligence · {latest?.plant_code ?? 'Plant'}</div><h1>Know what needs attention.</h1><p className="subtitle">A live management view built from validated production reporting.</p></div><div className="actions"><span className="status"><span className="pulse"/> LIVE DATA</span><button className="control" onClick={load}><RefreshCw size={13}/> Refresh</button></div></header>
      {error && <div className="panel error">{error}</div>}
      {!latest && !error && <div className="panel empty"><CheckCircle2 size={28}/><h2>Waiting for the first report</h2><p>Run the n8n reporting workflow. This dashboard will populate from <strong>industrial_reports</strong>.</p></div>}
      {latest && <>
        <section className="hero-grid" id="overview"><div className="panel hero"><div className="hero-title"><div><div className="eyebrow">Latest operating period</div><h2>{latest.plant_code} · {dateLabel(latest.period_start)} — {dateLabel(latest.period_end)}</h2><p>{insight(latest)}</p></div><div className="health"><span>Target attainment</span><strong>{pct(kpi.target_attainment)}</strong><div className="health-bar"><i style={{width:`${Math.min(100, Math.max(0, Number(kpi.target_attainment ?? 0)))}%`}}/></div></div></div><div className="signal"><div><span>QUALITY RATE</span><b>{pct(kpi.quality_rate)}</b></div><div><span>DOWNTIME</span><b>{fmt(kpi.downtime_minutes)} <small>min</small></b></div><div><span>PRODUCTION GAP</span><b>{fmt(kpi.production_gap)} <small>units</small></b></div></div></div><div className="panel attention"><div className="section-kicker"><span>Management attention</span><strong>{exceptions.length} signal{exceptions.length === 1 ? '' : 's'}</strong></div>{exceptions.length === 0 ? <div className="issue success"><CheckCircle2 size={17}/><div><b>No active exceptions</b><span>Latest period is within thresholds.</span></div></div> : exceptions.slice(0,4).map((e,i)=><div className="issue" key={`${e.record_id}-${i}`}><div className={`severity ${e.severity.toLowerCase()}`}/><div><b>{e.production_line_id} · {e.type.replaceAll('_',' ')}</b><span>{e.message} · {e.shift}</span></div></div>)}{exceptions.length > 4 && <div className="more">+ {exceptions.length - 4} more signals in report</div>}</div></section>
        <section className="chart-grid" id="performance"><div className="panel chart-panel wide"><div className="chart-head"><div><h3>Performance trajectory</h3><p>Is the plant improving or deteriorating?</p></div><span className="chart-badge"><TrendingUp size={12}/> {trend.length} periods</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{top:8,right:10,left:-8,bottom:4}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" tick={{fontSize:10}}/><YAxis domain={[80,100]} tick={{fontSize:10}} tickFormatter={v=>`${v}%`}/><Tooltip formatter={(v:any)=>`${Number(v).toFixed(1)}%`}/><Line type="monotone" dataKey="attainment" name="Target attainment" stroke="#1f8f5f" strokeWidth={3} dot={{r:3}}/><Line type="monotone" dataKey="quality" name="Quality rate" stroke="#19324d" strokeWidth={2} dot={{r:3}}/></LineChart></ResponsiveContainer></div><div className="legend"><span><i className="legend-green"/> Target attainment</span><span><i className="legend-navy"/> Quality rate</span></div></div><div className="panel chart-panel"><div className="chart-head"><div><h3>Production outcome</h3><p>Good output versus non-good units</p></div></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={qualityMix} dataKey="value" nameKey="name" innerRadius={64} outerRadius={88} paddingAngle={3} startAngle={90} endAngle={-270}><Cell fill="#1f8f5f"/><Cell fill="#d7dde5"/></Pie><Tooltip formatter={(v:any)=>fmt(Number(v))}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{pct(kpi.quality_rate)}</strong><span>good rate</span></div></div><div className="mini-split"><span><i className="legend-green"/> Good <b>{fmt(kpi.good_units)}</b></span><span><i className="legend-gray"/> Non-good <b>{fmt((kpi.produced_units ?? 0) - (kpi.good_units ?? 0))}</b></span></div></div></section>
        <section className="bottom-grid"><div className="panel chart-panel"><div className="chart-head"><div><h3>Exception concentration</h3><p>Lines generating the most management signals</p></div></div><div className="chart-wrap small"><ResponsiveContainer width="100%" height="100%"><BarChart data={lineExceptions} layout="vertical" margin={{top:8,right:20,left:5,bottom:5}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{fontSize:10}}/><YAxis type="category" dataKey="line" tick={{fontSize:10}} width={58}/><Tooltip/><Bar dataKey="count" name="Signals" radius={[0,5,5,0]} fill="#c77b11"/></BarChart></ResponsiveContainer></div></div><div className="panel chart-panel"><div className="chart-head"><div><h3>Latest production volume</h3><p>Target → produced → good</p></div></div><div className="chart-wrap small"><ResponsiveContainer width="100%" height="100%"><BarChart data={production} margin={{top:12,right:8,left:-18,bottom:5}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} tickFormatter={v=>new Intl.NumberFormat('en-US',{notation:'compact'}).format(v)}/><Tooltip formatter={(v:any)=>fmt(Number(v))}/><Bar dataKey="value" radius={[5,5,0,0]} fill="#19324d"/></BarChart></ResponsiveContainer></div></div></section>
        <section className="panel table-panel" id="reports"><div className="table-head"><div><h3>Recent reporting periods</h3><p>Every row opens the complete management report.</p></div><FileText size={17}/></div><table><thead><tr><th>Period</th><th>Attainment</th><th>Quality</th><th>Downtime</th><th>Signals</th></tr></thead><tbody>{reports.slice(0,8).map(r=><tr key={r.id}><td><Link href={`/reports/${r.id}`}>{dateLabel(r.period_start)} — {dateLabel(r.period_end)}</Link></td><td className={(r.kpi_data?.target_attainment ?? 0) >= 90 ? 'good':'bad'}>{pct(r.kpi_data?.target_attainment)}</td><td className={(r.kpi_data?.quality_rate ?? 0) >= 95 ? 'good':'warn'}>{pct(r.kpi_data?.quality_rate)}</td><td>{fmt(r.kpi_data?.downtime_minutes)} min</td><td><span className="signal-count">{r.exceptions_data?.length ?? 0}</span></td></tr>)}</tbody></table></section>
      </>}
    </main>
  </div>;
}
